### ISSUE TITLE
Direct data transfers between NVMe SSDs having CMB support

### ISSUE THREAD

**Issue by AnuradhaGHegde** [sbates130272/p2pmem-test#10]
Hi Stephen, 

I would like to know how p2pdma framework can be used for below scenario, 

1) I have 2 NVMe SSDs(A and B) with CMB ,WDS and RDS enabled
2) Transfer data from source SSD A to destination SSD B with no host memory involvement and less host CPU involvement

Please let me know how to achieve direct transfers between 2 drives using CMBs

Thanks and regards!!

**Comment by sbates130272** [comment]
That is the example given in the README.
