### ISSUE TITLE
Requires IOMMU to be disabled. Is there any other mechanism to perform P2P DMA when IOMMU is enabled

### ISSUE THREAD

**Issue by rerrabolu** [sbates130272/p2pmem-test#9]
In the read me it says IOMMU must be disabled including perhaps ACS.  So how can one perform P2P DMA when IOMMU is enabled on a system. 

Any thoughts?

Regards,
Ramesh

**Comment by sbates130272** [comment]
Later kernels should support IOMMU on for some systems. However it is hard to know in advance what is going to work,
